### ISSUE TITLE
error between log10 and log natural in OC Chl algo

### ISSUE THREAD

**Issue by Tristanovsk** [inrae/SISPPEO#1]
https://github.com/inrae/SISPPEO/blob/f516bb778b505739fdf320affe651b715ed75324/sisppeo/wcproducts/chla.py#L415            
https://github.com/inrae/SISPPEO/blob/f516bb778b505739fdf320affe651b715ed75324/sisppeo/wcproducts/chla.py#L420
need to change np.log to np.log10

**Comment by n-reynaud** [comment]
Thanks for noticing
The error has been fixed and changes will be available with the next update
